<#
.SYNOPSIS
  Pull the transcript of a YouTube video from its published caption track.

.DESCRIPTION
  No API keys, no download, no speech-to-text model, no LLM calls. YouTube has already
  transcribed the video: every video with speech carries a caption track, either uploaded
  by the channel or generated by YouTube's own ASR. Both are public and both are fetchable.

  Two layers, because one is not enough:

    INNERTUBE : POST to the player endpoint the YouTube clients themselves use. Returns the
                caption track list as JSON. Several client contexts are tried because any
                one of them can be refused on a given day.
    PAGE      : fall back to scraping ytInitialPlayerResponse out of the watch page HTML.

  Either layer yields a timed-text URL. That is fetched as json3 (falling back to YouTube's
  older XML) and rendered as plain text, timestamped lines, SRT, VTT or JSON.

.PARAMETER Url
  One or more video URLs or bare 11-character video IDs. watch, youtu.be, shorts, embed
  and live URLs are all accepted.

.PARAMETER InputFile
  Text or CSV file with one video URL or ID per line. Anything on the line that is not a
  recognisable video reference is ignored, so pasted lists with extra columns still work.

.PARAMETER Language
  Preferred caption language code. Defaults to en. Manual captions in that language win,
  then auto-generated ones, then anything else the video has.

.PARAMETER Translate
  Ask YouTube to machine-translate the chosen track into this language code.

.PARAMETER Format
  Text (flowing paragraphs, default), Lines, Timestamps, Srt, Vtt or Json.

.PARAMETER OutputPath
  File to write for a single video, or a directory when several are requested. Without it
  the transcript goes to stdout so it can be piped or redirected.

.PARAMETER ListTracks
  Report the caption tracks the video actually has and stop. Use this when the language
  you asked for came back empty.

.PARAMETER NoAuto
  Refuse auto-generated captions. Only human-authored tracks are accepted.

.EXAMPLE
  .\yt-transcript.ps1 https://www.youtube.com/watch?v=dQw4w9WgXcQ

.EXAMPLE
  .\yt-transcript.ps1 dQw4w9WgXcQ -Format Srt -OutputPath subs.srt

.EXAMPLE
  .\yt-transcript.ps1 -InputFile videos.txt -OutputPath .\transcripts -Format Timestamps

.NOTES
  Read-only. It requests the same public caption data the YouTube web player requests when
  you press CC. It does not download audio or video, does not sign in, and does not touch
  anything behind a paywall or an age gate.

  YouTube changes these endpoints without notice. When every layer fails at once, that is
  the usual cause rather than anything about the specific video.
#>
[CmdletBinding(DefaultParameterSetName = 'Direct')]
param(
  [Parameter(ParameterSetName = 'Direct', Mandatory = $true, Position = 0)]
  [string[]]$Url,

  [Parameter(ParameterSetName = 'File', Mandatory = $true)]
  [string]$InputFile,

  [string]$Language = 'en',
  [string]$Translate,

  [ValidateSet('Text', 'Lines', 'Timestamps', 'Srt', 'Vtt', 'Json')]
  [string]$Format = 'Text',

  [string]$OutputPath,

  # Report what caption tracks exist and stop.
  [switch]$ListTracks,

  # Reject YouTube's ASR captions. Human-authored tracks only.
  [switch]$NoAuto,

  # Seconds to wait between videos. Be polite on long lists.
  [int]$DelaySeconds = 0
)

$ErrorActionPreference = 'Continue'
$UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

# The InnerTube player endpoint, plus the client contexts worth trying. These keys are the
# ones YouTube's own clients ship publicly in their page source; they identify a client,
# they do not authenticate a user. Clients are tried in order and the first one that returns
# a caption list wins, because any single context can be refused on a given day.
$PLAYER_URL = 'https://www.youtube.com/youtubei/v1/player'
$CLIENTS = @(
  [pscustomobject]@{
    Name = 'ANDROID'; Version = '19.29.37'; Sdk = 30
    Key  = 'AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w'
    Ua   = 'com.google.android.youtube/19.29.37 (Linux; U; Android 11) gzip'
  }
  [pscustomobject]@{
    Name = 'IOS'; Version = '19.29.1'; Sdk = $null
    Key  = 'AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc'
    Ua   = 'com.google.ios.youtube/19.29.1 (iPhone16,2; U; CPU iOS 17_5_1 like Mac OS X)'
  }
  [pscustomobject]@{
    Name = 'WEB'; Version = '2.20240726.00.00'; Sdk = $null
    Key  = 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8'
    Ua   = $UA
  }
)

# ------------------------------------------------------------------- helpers --
function Get-Url {
  param([string]$u, [hashtable]$hdr, [string]$agent = $UA)
  try {
    $p = @{ Uri = $u; UserAgent = $agent; TimeoutSec = 25; UseBasicParsing = $true; ErrorAction = 'Stop' }
    if ($hdr) { $p.Headers = $hdr }
    return (Invoke-WebRequest @p).Content
  } catch { return $null }
}

# Walks a JSON string from an opening brace to its matching close, respecting quoted strings
# and escapes. A lazy regex cannot do this: caption text is full of braces and quotes.
function Get-BalancedJson {
  param([string]$Text, [int]$Start)
  $open = $Text[$Start]
  if ($open -eq '{') { $close = '}' } elseif ($open -eq '[') { $close = ']' } else { return $null }
  $depth = 0; $inStr = $false; $esc = $false
  for ($i = $Start; $i -lt $Text.Length; $i++) {
    $c = $Text[$i]
    if ($esc) { $esc = $false; continue }
    if ($inStr -and $c -eq '\') { $esc = $true; continue }
    if ($c -eq '"') { $inStr = -not $inStr; continue }
    if ($inStr) { continue }
    if ($c -eq $open) { $depth++ }
    elseif ($c -eq $close) { $depth--; if ($depth -eq 0) { return $Text.Substring($Start, $i - $Start + 1) } }
  }
  return $null
}

# Slice one object or array out of a large JSON blob by key. The player response runs to a
# megabyte of mostly irrelevant player config; parsing only the part we want keeps this
# fast and sidesteps ConvertFrom-Json's depth limits on Windows PowerShell 5.1.
function Get-JsonValueText {
  param([string]$Text, [string]$Key)
  if (-not $Text) { return $null }
  $m = [regex]::Match($Text, '"' + [regex]::Escape($Key) + '"\s*:\s*[\{\[]')
  if (-not $m.Success) { return $null }
  return Get-BalancedJson -Text $Text -Start ($m.Index + $m.Length - 1)
}

function Get-VideoId {
  param([string]$s)
  if (-not $s) { return $null }
  $s = $s.Trim().Trim('"', "'", ',')
  if ($s -match '^[A-Za-z0-9_-]{11}$') { return $s }
  $pats = @(
    '(?:youtube\.com|youtube-nocookie\.com)/watch\?(?:[^ ]*&)?v=([A-Za-z0-9_-]{11})',
    'youtu\.be/([A-Za-z0-9_-]{11})',
    '/(?:shorts|embed|live|v)/([A-Za-z0-9_-]{11})',
    '[?&]v=([A-Za-z0-9_-]{11})'
  )
  foreach ($p in $pats) {
    $m = [regex]::Match($s, $p)
    if ($m.Success) { return $m.Groups[1].Value }
  }
  return $null
}

function Get-InnertubeJson {
  param([string]$id)
  foreach ($c in $CLIENTS) {
    $client = [ordered]@{ clientName = $c.Name; clientVersion = $c.Version; hl = 'en'; gl = 'US' }
    if ($c.Sdk) { $client.androidSdkVersion = $c.Sdk }
    $body = [ordered]@{
      videoId        = $id
      context        = [ordered]@{ client = $client }
      contentCheckOk = $true
      racyCheckOk    = $true
    } | ConvertTo-Json -Depth 6 -Compress

    try {
      $r = Invoke-WebRequest -Uri "$($PLAYER_URL)?key=$($c.Key)&prettyPrint=false" -Method Post `
                             -Body $body -ContentType 'application/json; charset=utf-8' `
                             -UserAgent $c.Ua -TimeoutSec 25 -UseBasicParsing -ErrorAction Stop `
                             -Headers @{ 'X-Youtube-Client-Name' = '1'; 'X-Youtube-Client-Version' = $c.Version }
      $j = $r.Content
      if ($j -and $j -match '"captionTracks"') { return $j }
      # Playable but genuinely captionless: no other client will do better.
      if ($j -and $j -match '"videoDetails"') { $fallback = $j }
    } catch { }
  }
  if ($fallback) { return $fallback }
  return $null
}

function Get-WatchPageJson {
  param([string]$id)
  # bpctr and CONSENT skip the EU cookie interstitial, which otherwise replaces the player
  # response with a consent form.
  $u = "https://www.youtube.com/watch?v=$id&hl=en&bpctr=9999999999&has_verified=1"
  $html = Get-Url $u @{ 'Accept-Language' = 'en-US,en;q=0.9'; 'Cookie' = 'CONSENT=YES+cb; SOCS=CAI' }
  if (-not $html) { return $null }
  $m = [regex]::Match($html, 'ytInitialPlayerResponse\s*=\s*\{')
  if (-not $m.Success) { return $null }
  return Get-BalancedJson -Text $html -Start ($m.Index + $m.Length - 1)
}

function Get-PlayerJson {
  param([string]$id)
  $j = Get-InnertubeJson $id
  if ($j -and $j -match '"captionTracks"') { return $j }
  $p = Get-WatchPageJson $id
  if ($p -and $p -match '"captionTracks"') { return $p }
  # Neither had captions. Return whichever we got so the caller can report why.
  if ($j) { return $j }
  return $p
}

function Get-CaptionTracks {
  param([string]$playerJson)
  $cap = Get-JsonValueText $playerJson 'captionTracks'
  if (-not $cap) { return @() }
  try { return @($cap | ConvertFrom-Json) } catch { return @() }
}

function Get-TrackName {
  param($t)
  if ($t.name.simpleText) { return $t.name.simpleText }
  if ($t.name.runs)       { return ($t.name.runs | ForEach-Object { $_.text }) -join '' }
  return $t.languageCode
}

function Select-CaptionTrack {
  param($tracks, [string]$lang, [bool]$rejectAuto)
  $all = @($tracks)
  if ($rejectAuto) { $all = @($all | Where-Object { $_.kind -ne 'asr' }) }
  if (-not $all) { return $null }

  $manual = @($all | Where-Object { $_.kind -ne 'asr' })
  $auto   = @($all | Where-Object { $_.kind -eq 'asr' })

  # Human-authored in the requested language beats ASR in the requested language, which
  # beats anything else the video happens to carry.
  foreach ($set in @($manual, $auto)) {
    if (-not $set) { continue }
    $hit = $set | Where-Object { $_.languageCode -eq $lang } | Select-Object -First 1
    if ($hit) { return $hit }
    $hit = $set | Where-Object { $_.languageCode -like "$lang-*" } | Select-Object -First 1
    if ($hit) { return $hit }
  }
  if ($manual) { return $manual[0] }
  return $auto[0]
}

function ConvertFrom-TimedText {
  param([string]$raw)
  if (-not $raw -or -not $raw.Trim()) { return @() }

  $cues = New-Object System.Collections.ArrayList

  if ($raw.TrimStart().StartsWith('{')) {
    try { $j = $raw | ConvertFrom-Json } catch { return @() }
    foreach ($e in @($j.events)) {
      if ($e.aAppend) { continue }          # rolling-caption repeat of the previous line
      if (-not $e.segs) { continue }
      $t = (@($e.segs | ForEach-Object { $_.utf8 }) -join '')
      $t = ($t -replace '\s+', ' ').Trim()
      if (-not $t) { continue }
      $start = if ($null -ne $e.tStartMs)    { [int64]$e.tStartMs }    else { 0 }
      $dur   = if ($null -ne $e.dDurationMs) { [int64]$e.dDurationMs } else { 0 }
      [void]$cues.Add([pscustomobject]@{ StartMs = $start; DurMs = $dur; Text = $t })
    }
  } else {
    try { $x = [xml]$raw } catch { return @() }
    foreach ($n in @($x.transcript.text)) {
      # The XML track double-escapes: &amp;#39; has to be decoded twice to reach an apostrophe.
      $t = [System.Net.WebUtility]::HtmlDecode([System.Net.WebUtility]::HtmlDecode([string]$n.'#text'))
      $t = ($t -replace '\s+', ' ').Trim()
      if (-not $t) { continue }
      $start = if ($n.start) { [int64]([double]$n.start * 1000) } else { 0 }
      $dur   = if ($n.dur)   { [int64]([double]$n.dur   * 1000) } else { 0 }
      [void]$cues.Add([pscustomobject]@{ StartMs = $start; DurMs = $dur; Text = $t })
    }
  }

  # Give every cue a sane end: its own duration, clamped so it never runs into the next one.
  $arr = @($cues)
  for ($i = 0; $i -lt $arr.Count; $i++) {
    $end = if ($arr[$i].DurMs -gt 0) { $arr[$i].StartMs + $arr[$i].DurMs } else { $arr[$i].StartMs + 2000 }
    if ($i -lt $arr.Count - 1 -and $end -gt $arr[$i + 1].StartMs) { $end = $arr[$i + 1].StartMs }
    if ($end -le $arr[$i].StartMs) { $end = $arr[$i].StartMs + 100 }
    $arr[$i] | Add-Member -NotePropertyName EndMs -NotePropertyValue $end -Force
  }
  return $arr
}

function Get-Cues {
  param([string]$baseUrl, [string]$tlang)
  $suffix = if ($tlang) { '&tlang=' + [uri]::EscapeDataString($tlang) } else { '' }

  # json3 is the clean route. If it is refused, YouTube's older XML track still answers.
  $u = $baseUrl
  if ($u -notmatch '[?&]fmt=') { $u += '&fmt=json3' }
  $raw = Get-Url ($u + $suffix)
  if (-not $raw -or -not $raw.Trim()) { $raw = Get-Url ($baseUrl + $suffix) }

  return (ConvertFrom-TimedText $raw)
}

# ------------------------------------------------------------------ renderers --
function Format-Clock {
  param([int64]$ms, [string]$sep = '.', [switch]$Short)
  $ts = [timespan]::FromMilliseconds($ms)
  if ($Short) {
    if ($ts.TotalHours -ge 1) { return ('{0:d1}:{1:d2}:{2:d2}' -f [int]$ts.TotalHours, $ts.Minutes, $ts.Seconds) }
    return ('{0:d2}:{1:d2}' -f [int]$ts.TotalMinutes, $ts.Seconds)
  }
  return ('{0:d2}:{1:d2}:{2:d2}{3}{4:d3}' -f [int]$ts.TotalHours, $ts.Minutes, $ts.Seconds, $sep, $ts.Milliseconds)
}

function Format-Wrap {
  param([string]$s, [int]$w = 96)
  $out = New-Object System.Collections.ArrayList
  $line = ''
  foreach ($word in ($s -split '\s+')) {
    if (-not $word) { continue }
    if ($line -and ($line.Length + 1 + $word.Length) -gt $w) { [void]$out.Add($line); $line = $word }
    elseif ($line) { $line += ' ' + $word }
    else { $line = $word }
  }
  if ($line) { [void]$out.Add($line) }
  return ($out -join "`n")
}

# Caption cues are a few words each. Read as one line per cue they are unreadable, so cues
# are run back together and broken at a sentence end once the paragraph is long enough.
# ASR tracks carry no punctuation at all, hence the hard length backstop.
function Format-Paragraphs {
  param($cues)
  $paras = New-Object System.Collections.ArrayList
  $buf = ''
  foreach ($c in $cues) {
    $buf = if ($buf) { "$buf $($c.Text)" } else { $c.Text }
    if (($buf.Length -ge 600 -and $c.Text -match '[.!?]["'')]?$') -or $buf.Length -ge 1200) {
      [void]$paras.Add($buf); $buf = ''
    }
  }
  if ($buf) { [void]$paras.Add($buf) }
  return (@($paras | ForEach-Object { Format-Wrap $_ }) -join "`n`n")
}

function Format-Transcript {
  param($cues, [string]$fmt, $meta)
  switch ($fmt) {
    'Lines'      { return (@($cues | ForEach-Object { $_.Text }) -join "`n") }
    'Timestamps' { return (@($cues | ForEach-Object { '[{0}] {1}' -f (Format-Clock $_.StartMs -Short), $_.Text }) -join "`n") }
    'Srt' {
      $sb = New-Object System.Text.StringBuilder
      $i = 0
      foreach ($c in $cues) {
        $i++
        [void]$sb.AppendLine($i)
        [void]$sb.AppendLine(('{0} --> {1}' -f (Format-Clock $c.StartMs ','), (Format-Clock $c.EndMs ',')))
        [void]$sb.AppendLine($c.Text)
        [void]$sb.AppendLine()
      }
      return $sb.ToString().TrimEnd()
    }
    'Vtt' {
      $sb = New-Object System.Text.StringBuilder
      [void]$sb.AppendLine('WEBVTT')
      [void]$sb.AppendLine()
      foreach ($c in $cues) {
        [void]$sb.AppendLine(('{0} --> {1}' -f (Format-Clock $c.StartMs '.'), (Format-Clock $c.EndMs '.')))
        [void]$sb.AppendLine($c.Text)
        [void]$sb.AppendLine()
      }
      return $sb.ToString().TrimEnd()
    }
    'Json' {
      return ([pscustomobject]@{
        videoId  = $meta.VideoId
        title    = $meta.Title
        author   = $meta.Author
        language = $meta.Language
        track    = $meta.Track
        auto     = $meta.Auto
        cues     = @($cues | ForEach-Object {
                     [pscustomobject]@{ start = [math]::Round($_.StartMs / 1000, 3)
                                        end   = [math]::Round($_.EndMs   / 1000, 3)
                                        text  = $_.Text }
                   })
      } | ConvertTo-Json -Depth 5)
    }
    default { return (Format-Paragraphs $cues) }
  }
}

function Get-SafeFileName {
  param([string]$s, [int]$max = 70)
  if (-not $s) { return 'transcript' }
  # Explicit set rather than GetInvalidFileNameChars(): on Linux that returns only '/', which
  # would happily write a name that breaks the moment the file reaches Windows.
  $s = ($s -replace '[<>:"/\\|?*\x00-\x1f]', '-')
  $s = ($s -replace '\s+', ' ').Trim(' ', '.')
  if ($s.Length -gt $max) { $s = $s.Substring(0, $max).Trim() }
  if (-not $s) { return 'transcript' }
  return $s
}

function Write-TextFile {
  param([string]$path, [string]$text)
  $dir = Split-Path -Parent $path
  if ($dir -and -not (Test-Path $dir)) { [void](New-Item -ItemType Directory -Path $dir -Force) }
  [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding $false))
}

# ---------------------------------------------------------------------- main --
if ($PSCmdlet.ParameterSetName -eq 'File') {
  if (-not (Test-Path $InputFile)) { throw "Input file not found: $InputFile" }
  $requests = @(Get-Content $InputFile | Where-Object { $_ -and $_.Trim() -and -not $_.TrimStart().StartsWith('#') })
} else {
  $requests = @($Url)
}
if (-not $requests) { throw "Nothing to do: no video URLs or IDs supplied." }

$EXT = @{ Text = 'txt'; Lines = 'txt'; Timestamps = 'txt'; Srt = 'srt'; Vtt = 'vtt'; Json = 'json' }

# A directory target, either because it exists or because several videos were asked for.
$multi = $requests.Count -gt 1
$asDir = $false
if ($OutputPath) {
  $asDir = $multi -or (Test-Path -Path $OutputPath -PathType Container) -or -not [System.IO.Path]::GetExtension($OutputPath)
}

$n = 0
$total = $requests.Count
$ok = 0
$failed = New-Object System.Collections.ArrayList

foreach ($req in $requests) {
  $n++
  $id = Get-VideoId $req

  if (-not $id) {
    [void]$failed.Add([pscustomobject]@{ Input = $req; Reason = 'not a YouTube URL or video ID' })
    Write-Host ("[{0}/{1}] {2,-14} -> not a YouTube URL or video ID" -f $n, $total, $req) -ForegroundColor DarkGray
    continue
  }

  $player = Get-PlayerJson $id
  if (-not $player) {
    [void]$failed.Add([pscustomobject]@{ Input = $id; Reason = 'no player response (network, or YouTube refused every client)' })
    Write-Host ("[{0}/{1}] {2,-14} -> no player response" -f $n, $total, $id) -ForegroundColor Yellow
    continue
  }

  # videoDetails is absent when the video is private, removed or age-gated. Say which.
  $details = $null
  $dText = Get-JsonValueText $player 'videoDetails'
  if ($dText) { try { $details = $dText | ConvertFrom-Json } catch { } }

  $title  = if ($details.title)  { [string]$details.title }  else { $id }
  $author = if ($details.author) { [string]$details.author } else { '' }

  $tracks = Get-CaptionTracks $player

  if (-not $tracks) {
    $status = ''
    $sm = [regex]::Match($player, '"status"\s*:\s*"([A-Z_]+)"')
    if ($sm.Success) { $status = $sm.Groups[1].Value }
    $rm = [regex]::Match($player, '"reason"\s*:\s*\{\s*"simpleText"\s*:\s*"([^"]{0,160})"')
    if (-not $rm.Success) { $rm = [regex]::Match($player, '"reason"\s*:\s*"([^"]{0,160})"') }

    $why = if ($rm.Success)            { $rm.Groups[1].Value }
           elseif ($status -and $status -ne 'OK') { "not playable anonymously ($status)" }
           else                        { 'no caption track published' }

    [void]$failed.Add([pscustomobject]@{ Input = $id; Reason = $why })
    Write-Host ("[{0}/{1}] {2,-14} -> {3}" -f $n, $total, $id, $why) -ForegroundColor Yellow
    if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
    continue
  }

  if ($ListTracks) {
    Write-Host ("[{0}/{1}] {2}  {3}" -f $n, $total, $id, $title) -ForegroundColor Cyan
    $tracks | ForEach-Object {
      [pscustomobject]@{
        Code   = $_.languageCode
        Kind   = if ($_.kind -eq 'asr') { 'auto' } else { 'manual' }
        Name   = Get-TrackName $_
      }
    } | Format-Table -AutoSize | Out-String | Write-Host
    if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
    continue
  }

  $track = Select-CaptionTrack $tracks $Language ([bool]$NoAuto)
  if (-not $track) {
    $have = (@($tracks | ForEach-Object { $_.languageCode }) | Select-Object -Unique) -join ', '
    $why = "no track matched (-NoAuto excluded every track; available: $have)"
    [void]$failed.Add([pscustomobject]@{ Input = $id; Reason = $why })
    Write-Host ("[{0}/{1}] {2,-14} -> {3}" -f $n, $total, $id, $why) -ForegroundColor Yellow
    continue
  }

  $cues = Get-Cues $track.baseUrl $Translate
  if (-not $cues) {
    [void]$failed.Add([pscustomobject]@{ Input = $id; Reason = 'caption track listed but returned no cues' })
    Write-Host ("[{0}/{1}] {2,-14} -> track listed but empty" -f $n, $total, $id) -ForegroundColor Yellow
    continue
  }

  $isAuto = ($track.kind -eq 'asr')
  $meta = [pscustomobject]@{
    VideoId  = $id
    Title    = $title
    Author   = $author
    Language = if ($Translate) { $Translate } else { [string]$track.languageCode }
    Track    = Get-TrackName $track
    Auto     = $isAuto
  }

  $body = Format-Transcript $cues $Format $meta

  if ($OutputPath) {
    # A header only makes sense on prose. SRT, VTT and JSON have to stay machine-readable.
    if ($Format -in @('Text', 'Lines', 'Timestamps')) {
      $head = @("$title", $(if ($author) { $author } else { $null }),
                "https://www.youtube.com/watch?v=$id",
                ("{0} captions, {1}, {2} cues" -f $(if ($isAuto) { 'auto-generated' } else { 'manual' }), $meta.Language, $cues.Count),
                '') | Where-Object { $null -ne $_ }
      $body = ($head -join "`n") + "`n" + $body
    }
    $path = if ($asDir) {
      Join-Path $OutputPath ("{0} - {1}.{2}" -f $id, (Get-SafeFileName $title), $EXT[$Format])
    } else { $OutputPath }
    Write-TextFile $path $body
    Write-Host ("[{0}/{1}] {2,-14} -> {3}  ({4} cues, {5}, {6}) {7}" -f $n, $total, $id, $title, $cues.Count,
                $meta.Language, $(if ($isAuto) { 'auto' } else { 'manual' }), $path) -ForegroundColor Green
  } else {
    Write-Host ("[{0}/{1}] {2,-14} -> {3}  ({4} cues, {5}, {6})" -f $n, $total, $id, $title, $cues.Count,
                $meta.Language, $(if ($isAuto) { 'auto' } else { 'manual' })) -ForegroundColor Green
    Write-Output $body
  }

  $ok++
  if ($DelaySeconds -gt 0) { Start-Sleep -Seconds $DelaySeconds }
}

if ($total -gt 1 -or $failed.Count) {
  Write-Host ""
  Write-Host ("Transcribed {0} of {1}." -f $ok, $total)
  # A tool that silently drops what it could not fetch reports a confident blank.
  if ($failed.Count) {
    Write-Host ("Not transcribed: {0}" -f $failed.Count) -ForegroundColor Yellow
    $failed | ForEach-Object { Write-Host ("  {0}: {1}" -f $_.Input, $_.Reason) -ForegroundColor DarkGray }
  }
}
